### ISSUE TITLE
ENH: support .hoc format for morphologies

### ISSUE THREAD

**Issue by abast** [BlueBrain/BluePyOpt#253] opened 2018-08-08 05:53 UTC
I've been trying to follow these two examples:

    examples/simplecell/simplecell.ipynb
    examples l5pc/L5PC.ipynb

However, I cannot load the morphology with the `ephys.morphologies.NrnFileMorphology` method as it only supports the .asc and .swc format. 

(How) can a morphology described in the .hoc format be used within BluePyOpt?

**Comment by wvangeit** [comment] 2018-08-08 11:43
For the general case, I'm not sure how easy it will be to use a morphology described in HOC. 
Is there a possibility to share that morphology ?
The problem is that HOC will allow you to describe the morph in several ways which might be incompatible with how the ephys layer of BluePyOpt assume things are set up.

I would say the easiest way would be to possible convert the HOC morph into SWC or ASC (if possible at all of course ...).

**Comment by abast** [comment] 2018-08-08 12:26
Thanks for the quick response. I could an share an exemplary morphology with you .. where / how can I reach you?

**Comment by wvangeit** [comment] 2018-08-09 12:34
You can send it to the email address on this page: https://people.epfl.ch/werner.vangeit

**Comment by abast** [comment] 2018-08-09 13:28
Hm .. I get a "Internal Server Error" message if I click on that link

**Comment by wvangeit** [comment] 2018-08-16 11:28
We discussed this by email. I will close this for now. You can reopen it if/when you need more help.

For future reference: we provided you with a converter to dump your morphology to SWC.

**Closed by wvangeit** 2018-08-16 11:28 UTC
