### ISSUE TITLE
How to chose eta, crossing over probability and mutation probability

### ISSUE THREAD

**Issue by abast** [BlueBrain/BluePyOpt#254] opened 2018-08-15 15:44 UTC
The class `DEAPOptimisation `has parameters, that affect the optimization, most importantly `mutpb`, `cxpb `and `eta`. How do you usually chose these parameters? I see, that they default to `cxpb = 1`, `mutpb = 1`, `eta = 10`. In the example of the L5PC, the default values are (implicitly) used in the toy example of 2 generations.  in gaupnerbrunelstdp, `eta=20, mutpb=0.3, cxpb=0.7` is used. Why? Is there a rule of thumb, which parameters give good results? 

If I use 1000 individuals and 1000 generations, I see, that a feasible solution is only found in ~30% of the optimizations and I am therefore wondering, if I just choose the parameters wrong. Or is this the expected success rate?

**Comment by wvangeit** [comment] 2018-08-15 16:40
Unfortunately that's not a trivial problem.
First of all, if you want to know what the eta means, you can start e.g. here:
http://repository.ias.ac.in/9415/1/318.pdf
Figure 1 shows the simulated binary crossover operator for different eta. The mutation operator uses eta in a similar way.

In general we find the value of eta (and cxpb/mutpb) by trial and error while running test optimizations. The problem is that the best values will depend on the exact problem: dimensionality of parameter and objective space, complexity of the search space, etc.

I assume @pineider used a different eta=20 for graupnerbrunelstdp because he had some intuition that searching a bit narrower around the existing population was more useful.

About the ~30% success rate. E.g. it will already depend on the exact problem you're optimizing. But I must say that in general, for e.g. the L5PC cell, we also run with e.g. 4 different seeds and pick the best model generated by these 4.

**Comment by abast** [comment] 2018-08-16 09:59
Thanks for that explanation. It is really helpful. Did you use the default values (mutpb = 1, cxpb = 1, eta = 10) and 1000 individuals with 500 generations for the L5PC example? 

Currently, I am running 1000 generations. My impression is that a good solution is usually found rather in the beginning (up to around 300 generations) or it is not found at all .. so I should probably run fewer generations and try more optimizations with different seeds. Did you make a similar observation?

**Comment by abast** [comment] 2018-08-16 11:50
I understand that it highly depends on the problem. Still, it is nice to be reassured that we came to the same observations. Again, thanks for sharing your experience.

**Comment by wvangeit** [comment] 2018-08-16 12:12
Ok, indeed good to see the observations confirmed.
Will close this issue for now, let us know if you need more help.

**Closed by wvangeit** 2018-08-16 12:12 UTC
Labels: help wanted
